---
  - hosts: webservers
    become: true
    gather_facts: no
    vars:
      my_demo_folder_path: "/home/ec2-user"
      server_name: "52.215.190.175" #ansible_default_ipv4.address
      document_root: "/var/www/html"
      app_root: html_demo_site-main

    tasks: 
      - name: Creating a new folder
        file:
          path: "{{ my_demo_folder_path }}"
          state: directory
          owner: ec2-user
    
      - name: install Nginx
        yum:
          name: https://nginx.org/packages/mainline/amzn2/2/x86_64/RPMS/nginx-1.21.4-1.amzn2.ngx.x86_64.rpm
          state: latest

      - name: Copy website files to the server's document root
        copy:
          src: "{{ app_root }}"
          dest: "{{ document_root }}"
          mode: preserve

      - name: Creating sites-available
        file:
          path: /etc/nginx/sites-available
          state: directory
          mode: '0755'
          group: root
          owner: ec2-user

      - name: Creating sites-enabled
        file:
          path: /etc/nginx/sites-enabled
          state: directory
          mode: '0755'
          group: root
          owner: ec2-user
    
      - name: Apply Nginx template
        template:
          src: files/nginx.conf.j2
          dest: /etc/nginx/sites-available/site
        notify: Restart Nginx

      - name: Enable new site                  #ERROR "refusing to convert from directory to symlink for /etc/nginx/sites-enabled/site"
        file:
          src: /etc/nginx/sites-available/site
          dest: /etc/nginx/sites-enabled/site
          state: link
        notify: Restart Nginx

    handlers:
      - name: Restart Nginx
        service:
          name: nginx
          state: restarted
